create table if not exists public.businesses(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,name text not null,slug text not null unique,tagline text,description text,logo_url text,whatsapp text,instagram text,is_published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,name text not null,created_at timestamptz not null default now(),unique(business_id,name));
create table if not exists public.products(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,category_id uuid references public.categories(id) on delete set null,name text not null,slug text not null,description text,short_description text,price numeric(10,2) not null default 0,image_url text,includes jsonb not null default '[]'::jsonb,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(business_id,slug));
create index if not exists businesses_owner_id_idx on public.businesses(owner_id);create index if not exists categories_business_id_idx on public.categories(business_id);create index if not exists products_business_id_idx on public.products(business_id);create index if not exists products_category_id_idx on public.products(category_id);
alter table public.businesses enable row level security;alter table public.categories enable row level security;alter table public.products enable row level security;
drop policy if exists "business owners manage businesses" on public.businesses;create policy "business owners manage businesses" on public.businesses for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists "business owners manage categories" on public.categories;create policy "business owners manage categories" on public.categories for all to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid())) with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));
drop policy if exists "business owners manage products" on public.products;create policy "business owners manage products" on public.products for all to authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid())) with check(exists(select 1 from public.businesses b where b.id=business_id and b.owner_id=auth.uid()));
drop policy if exists "public view published businesses" on public.businesses;create policy "public view published businesses" on public.businesses for select to anon,authenticated using(is_published=true);
drop policy if exists "public view categories" on public.categories;create policy "public view categories" on public.categories for select to anon,authenticated using(exists(select 1 from public.businesses b where b.id=business_id and b.is_published=true));
drop policy if exists "public view active products" on public.products;create policy "public view active products" on public.products for select to anon,authenticated using(is_active=true and exists(select 1 from public.businesses b where b.id=business_id and b.is_published=true));

-- Create this bucket in Supabase Storage before using product image uploads.
insert into storage.buckets(id,name,public) values('business-assets','business-assets',true) on conflict(id) do update set public=true;
drop policy if exists "public can view business assets" on storage.objects;
create policy "public can view business assets" on storage.objects for select to anon,authenticated using(bucket_id='business-assets');
drop policy if exists "business owners can upload assets" on storage.objects;
create policy "business owners can upload assets" on storage.objects for insert to authenticated with check(bucket_id='business-assets' and exists(select 1 from public.businesses b where b.id=(storage.foldername(name))[1]::uuid and b.owner_id=auth.uid()));
drop policy if exists "business owners can update assets" on storage.objects;
create policy "business owners can update assets" on storage.objects for update to authenticated using(bucket_id='business-assets' and exists(select 1 from public.businesses b where b.id=(storage.foldername(name))[1]::uuid and b.owner_id=auth.uid())) with check(bucket_id='business-assets' and exists(select 1 from public.businesses b where b.id=(storage.foldername(name))[1]::uuid and b.owner_id=auth.uid()));
drop policy if exists "business owners can delete assets" on storage.objects;
create policy "business owners can delete assets" on storage.objects for delete to authenticated using(bucket_id='business-assets' and exists(select 1 from public.businesses b where b.id=(storage.foldername(name))[1]::uuid and b.owner_id=auth.uid()));
